all:
	gcc -Wall -Wno-format -Wno-unused-function -Wno-implicit-function-declaration -Wno-parentheses -fno-stack-protector -shared -o mylibc.so -fPIC mylibc.c
	# gcc -c -fPIC mylibc.c -o mylibc.o
	# gcc mylibc.o -shared -o mylibc.so
